#!/bin/bash

if [ -z "$1" ]
    then
    echo ""
    echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
    echo "*                                                           *"
    echo "*  usage: bash orf_check *.orf.fa                              *"
    echo "*                                                           *"
    echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
    echo ""
    exit 0
else
    NAME=$(echo ${1}|awk -F"." '{print $1}')
    grep ">" $1 | sed 's/>//g' | awk '{print $1}' > ${NAME}.orf.number
fi
