# 
# Sunbeam configuration file
#
# Defining samples:
#   Run 'sunbeam list_samples <data_dir>' to create a list of samples and
#   associated fastq.gz files. Samples must be in gzipped fastq format.
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: /media/lorax/users/guanxiang/1_igram/liang2019/input/wet.input/discovery.virome
  output_fp: sunbeam_output
  samplelist_fp: samples.csv
  paired_end: true
  download_reads: false
  version: 2.0.0

# Quality control
qc:
  suffix: qc
  # Trimmomatic
  threads: 4
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4, 15]
  minlen: 36
  adapter_fp: /home/guanxiang/miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa
  # Cutadapt
  fwd_adapters: []
  rev_adapters: []
  # Komplexity
  kz_threshold: 0.55
  # Decontam.py
  pct_id: 0.5
  frac: 0.6
  host_fp: '/media/lorax/users/guanxiang/1_igram/liang2019/input/databae/sunbeam.host.genome'


# Taxonomic classifications
classify:
  suffix: classify
  threads: 4
  kraken_db_fp: '/media/lorax/users/guanxiang/1_igram/liang2019/input/database/kraken.db'

# Contig assembly
assembly:
  suffix: assembly
  min_length: 300
  threads: 4

# Contig annotation
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500

blast:
  threads: 4

blastdbs:
  root_fp: ''

mapping:
  suffix: mapping
  genomes_fp: '/media/lorax/users/guanxiang/1_igram/liang2019/input/database/anmimal.virus.genome'
  samtools_opts: ''
  threads: 4

download:
  suffix: download
  threads: 4
sbx_dedup:
  threads: 4
